name: Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
      - name: Github Release create, update, and upload assets
        uses: meeDamian/github-release@v2.0.3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          tag: ${{ github.event.head_commit.message }}
          name: v${{ github.event.head_commit.message }}
          draft: true
          files: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          gzip: false
